// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rune/poa/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// owner is the initial owner of the validator pool in Bech32 format.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// validators defines the initial list of validators.
	Validators []Validator `protobuf:"bytes,3,rep,name=validators,proto3" json:"validators"`
	// privilege_assignments defines the initial list of validator privilege
	// assignments.
	PrivilegeAssignments []ValidatorPrivilegeAssignment `protobuf:"bytes,4,rep,name=privilege_assignments,json=privilegeAssignments,proto3" json:"privilege_assignments"`
	// emergency_team is the initial global emergency team in Bech32 format. An
	// empty value means the role is not granted.
	EmergencyTeam string `protobuf:"bytes,5,opt,name=emergency_team,json=emergencyTeam,proto3" json:"emergency_team,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d55d187c6050f37, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GenesisState) GetValidators() []Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *GenesisState) GetPrivilegeAssignments() []ValidatorPrivilegeAssignment {
	if m != nil {
		return m.PrivilegeAssignments
	}
	return nil
}

func (m *GenesisState) GetEmergencyTeam() string {
	if m != nil {
		return m.EmergencyTeam
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "rune.poa.v1.GenesisState")
}

func init() { proto.RegisterFile("rune/poa/v1/genesis.proto", fileDescriptor_0d55d187c6050f37) }

var fileDescriptor_0d55d187c6050f37 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbd, 0x4e, 0x72, 0x31,
	0x18, 0xc7, 0xcf, 0xe1, 0x2b, 0x79, 0xcb, 0xab, 0xc3, 0x11, 0xcc, 0x91, 0xe1, 0x48, 0x4c, 0x4c,
	0x60, 0xf0, 0x34, 0xe0, 0xea, 0x22, 0x0e, 0xae, 0x04, 0x8d, 0x83, 0x0b, 0x29, 0xf0, 0xa4, 0x34,
	0xa1, 0x7d, 0x9a, 0xb6, 0x1c, 0xe5, 0x2e, 0xbc, 0x06, 0xaf, 0x86, 0x91, 0xd1, 0xc9, 0x18, 0xb8,
	0x11, 0x43, 0xf9, 0x08, 0x46, 0xb7, 0xa7, 0xff, 0x8f, 0x5f, 0xd2, 0x3f, 0x39, 0x33, 0x53, 0x05,
	0x54, 0x23, 0xa3, 0x59, 0x8b, 0x72, 0x50, 0x60, 0x85, 0x4d, 0xb5, 0x41, 0x87, 0x51, 0x79, 0x6d,
	0xa5, 0x1a, 0x59, 0x9a, 0xb5, 0x6a, 0x15, 0x8e, 0x1c, 0xbd, 0x4e, 0xd7, 0xd7, 0x26, 0x52, 0xab,
	0x1e, 0xb6, 0xd7, 0x49, 0x2f, 0x5f, 0xbc, 0xe7, 0xc8, 0xff, 0xfb, 0x0d, 0xeb, 0xc1, 0x31, 0x07,
	0x51, 0x8b, 0x94, 0x34, 0x33, 0x4c, 0xda, 0x38, 0xac, 0x87, 0x8d, 0x72, 0xfb, 0x24, 0x3d, 0x60,
	0xa7, 0x5d, 0x6f, 0x75, 0x0a, 0xf3, 0xcf, 0xf3, 0xa0, 0xb7, 0x0d, 0x46, 0x15, 0x52, 0xc4, 0x17,
	0x05, 0x26, 0xce, 0xd5, 0xc3, 0xc6, 0xbf, 0xde, 0xe6, 0x11, 0xdd, 0x10, 0x92, 0xb1, 0x89, 0x18,
	0x31, 0x87, 0xc6, 0xc6, 0xf9, 0x7a, 0xbe, 0x51, 0x6e, 0x9f, 0xfe, 0x80, 0x3d, 0xed, 0xec, 0x2d,
	0xef, 0x20, 0x1f, 0x8d, 0x48, 0x55, 0x1b, 0x91, 0x89, 0x09, 0x70, 0xe8, 0x33, 0x6b, 0x05, 0x57,
	0x12, 0x94, 0xb3, 0x71, 0xc1, 0x83, 0x9a, 0x7f, 0x83, 0xba, 0xbb, 0xca, 0xed, 0xbe, 0xb1, 0x65,
	0x57, 0xf4, 0x6f, 0xcb, 0x46, 0x97, 0xe4, 0x18, 0x24, 0x18, 0x0e, 0x6a, 0x38, 0xeb, 0x3b, 0x60,
	0x32, 0x2e, 0xfa, 0x2f, 0x1c, 0xed, 0xd5, 0x47, 0x60, 0xb2, 0x73, 0x37, 0x5f, 0x26, 0xe1, 0x62,
	0x99, 0x84, 0x5f, 0xcb, 0x24, 0x7c, 0x5b, 0x25, 0xc1, 0x62, 0x95, 0x04, 0x1f, 0xab, 0x24, 0x78,
	0x6e, 0x72, 0xe1, 0xc6, 0xd3, 0x41, 0x3a, 0x44, 0x49, 0xc7, 0x88, 0x23, 0x31, 0x95, 0x57, 0x02,
	0x77, 0x27, 0x7d, 0xf5, 0x83, 0xbb, 0x99, 0x06, 0x3b, 0x28, 0xf9, 0xc1, 0xaf, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x48, 0x49, 0x71, 0x85, 0xc7, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EmergencyTeam) > 0 {
		i -= len(m.EmergencyTeam)
		copy(dAtA[i:], m.EmergencyTeam)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.EmergencyTeam)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PrivilegeAssignments) > 0 {
		for iNdEx := len(m.PrivilegeAssignments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PrivilegeAssignments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PrivilegeAssignments) > 0 {
		for _, e := range m.PrivilegeAssignments {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = len(m.EmergencyTeam)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, Validator{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrivilegeAssignments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrivilegeAssignments = append(m.PrivilegeAssignments, ValidatorPrivilegeAssignment{})
			if err := m.PrivilegeAssignments[len(m.PrivilegeAssignments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyTeam", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EmergencyTeam = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
