{
 "title": "Rune Nodes (Public)",
 "tags": [
  "public",
  "rune"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Monitored nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(chain_id) (sum by(moniker) (up{chain_id=\"rune_6590-1\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (experimental)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "min by(moniker) (up{chain_id=\"rune_6590-1\"})",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "min by(moniker) (latest_block{chain_id=\"rune_6590-1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest block time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "min by(moniker) (latest_timestamp{chain_id=\"rune_6590-1\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}