package staking

// EvmByteCode is the EVM bytecode of the Staking precompile. This code is
// returned by eth_getCode and ensures the precompile address is detected as a
// smart contract by external services. Note: It should NOT contain a 0x prefix
//
// WARNING! This value is used in the InitChain ABCI hook and affects the app state hash.
// Remember to always update this constant upon changes in the precompile ABI.
//
// This bytecode was generated by compiling the StakingCaller contract
// (core/precompile/contracts/StakingCaller.sol) in the core/precompile Hardhat
// package and extracting deployedBytecode from the build artifacts.
//
// DO NOT EDIT BY HAND. Regenerate with `make precompile-gen` (or run
// `core/precompile/scripts/generate-bytecode.sh` after `npx hardhat compile`).
//
// TODO: currently empty. Populate by compiling StakingCaller.sol, then running
// the generator (`cd core/precompile && npx hardhat compile`, then
// `./scripts/generate-bytecode.sh`).
const EvmByteCode = ""
